// English text for the member dashboard's My forms card.
export const DASHBOARD_COPY = {
  "dash.account.connected": "Account connected",
  "dash.account.kingdom": "Kingdom {id}",
  "dash.account.mysticTrial": "Mystic Trial",
  "dash.account.noAdmin": "Your member account does not have administrator access.",
  "dash.account.noAlliance": "No alliance listed",
  "dash.account.power": "Power",
  "dash.account.session": "Signed in with Kingshot. Your session stays active for 30 days unless you log out.",
  "dash.account.title": "Your account",
  "dash.allDone": "You're all caught up.",
  "dash.allDoneHint": "You can still change your answers any time while a form is open.",
  "dash.alsoOpen": "Also open now",
  "dash.footer": "Times are shown in your own time zone.",
  "dash.formsHeading": "Your forms",
  "dash.greeting": "Hi {name}",
  "dash.left.one": "You have {count} form left to do.",
  "dash.left.other": "You have {count} forms left to do.",
  "dash.loadError": "We could not load your forms just now. Try again in a moment.",
  "dash.loadErrorLink": "Open the forms page",
  "dash.loading": "Loading your forms…",
  "dash.mainAria": "Member dashboard",
  "dash.more.admin": "Admin dashboard",
  "dash.more.allForms": "All forms",
  "dash.more.deadlines": "Deadlines",
  "dash.more.dueSoon": "Due soon",
  "dash.more.estimated": "estimated date, not confirmed",
  "dash.more.events": "Events & schedules",
  "dash.more.giftCodes": "Gift codes",
  "dash.more.guides": "Guides",
  "dash.more.hint": "Tools, events, gift codes, guides",
  "dash.more.noDeadlines": "No dated events or deadlines are scheduled yet.",
  "dash.more.title": "More",
  "dash.more.tools": "Upgrade calculators & tools",
  "dash.moreNavAria": "More destinations",
  "dash.nothingOpen": "Nothing to fill in right now. Check back when leadership opens a form.",
  "dash.pageTitle": "Dashboard",
  "dash.power.help": "Gear, charms, scanner",
  "dash.power.title": "Power Profile (optional)",
  "dash.power.todo": "Not started",
  "dash.result.label": "Result",
  "dash.result.new": "New: your appointment is ready",
  "dash.result.open": "Open",
  "dash.result.see": "See my appointment",
  "dash.sideAria": "Settings and more",
  "dash.wordmarkAria": "K710 home",
  "form.date.before": "Before {date}",
  "form.date.none": "No deadline set yet",
  "form.date.opens": "Opens {date}",
  "form.dragon.help": "Your troops and heroes for the event",
  "form.dragon.title": "Flamedragon Tyrant",
  "form.joiner.help": "When you can play · troops and heroes",
  "form.joiner.title": "KvK Availability",
  "form.noble.help": "Book your troop training time",
  "form.noble.title": "Noble Advisor",
  "form.prep.help": "Chief Minister buffs · before prep days",
  "form.prep.title": "KvK Prep & Appointments",
  "form.saved": "Saved {date}",
  "formButton.aria": "{action}: {form}",
  "formButton.change": "Change answers",
  "formButton.check": "Check and save",
  "formButton.closed": "Closed",
  "formButton.fill": "Fill in",
  "formButton.numberAria": "Form {number}",
  "formStatus.carry": "Check and save",
  "formStatus.closed": "Closed",
  "formStatus.done": "Done",
  "formStatus.soon": "Opens soon",
  "formStatus.todo": "Not done"
};

/** t(key, vars): English text with {name} placeholders filled in. Plural keys use key.one / key.other. */
export function dashT(key, vars = {}) {
  let text = DASHBOARD_COPY[key];
  if (text === undefined && typeof vars.count === 'number') text = DASHBOARD_COPY[`${key}.${vars.count === 1 ? 'one' : 'other'}`];
  if (text === undefined) return key;
  return text.replace(/\{(\w+)\}/g, (m, name) => (vars[name] === undefined ? m : String(vars[name])));
}
